### ISSUE TITLE
AVG pooling

### ISSUE THREAD

**Issue by joihn** [nspunn1993/BT-Unet#2]
Hello, 

I'm also trying to use BT for segmentation

I've noticed in your paper code, that the global average pooling restrict is a huge bottleneck:
![image](https://user-images.githubusercontent.com/11663917/199739314-d688b2cd-36d7-4824-ba96-3e5ab2946a91.png)

According to my experiments, in your BT-Unet:
before pooling: batch x 16x16x256
After pooling: batchx256,

Then we are left with only 256 value per image to be fed to the FC layers, which is very few I think. 

In the original BT paper, they also do an AVG pooling (well, actually it's built in into the Resnet they use), 
before pooling: batch x2048x7x7
after pooling: batch x2048x1x1

As you can see, original paper has much more data per image (2048 instead of 256)

What do you think ? Am I correct ?

**Comment by joihn** [comment]
Hum, actually it might simply be a story about the encoder size, 
reset 50 is 25'000 K  params
Your unet is 353 K params,
Thus it make sens that the embedding is smaller.

**Comment by JackHeroFly** [comment]
> Hello,
> 
> I'm also trying to use BT for segmentation
> 
> I've noticed in your paper code, that the global average pooling restrict is a huge bottleneck: ![image](https://user-images.githubusercontent.com/11663917/199739314-d688b2cd-36d7-4824-ba96-3e5ab2946a91.png)
> 
> According to my experiments, in your BT-Unet: before pooling: batch x 16x16x256 After pooling: batchx256,
> 
> Then we are left with only 256 value per image to be fed to the FC layers, which is very few I think.
> 
> In the original BT paper, they also do an AVG pooling (well, actually it's built in into the Resnet they use), before pooling: batch x2048x7x7 after pooling: batch x2048x1x1
> 
> As you can see, original paper has much more data per image (2048 instead of 256)
> 
> What do you think ? Am I correct ?



> Hello,
> 
> I'm also trying to use BT for segmentation
> 
> I've noticed in your paper code, that the global average pooling restrict is a huge bottleneck: ![image](https://user-images.githubusercontent.com/11663917/199739314-d688b2cd-36d7-4824-ba96-3e5ab2946a91.png)
> 
> According to my experiments, in your BT-Unet: before pooling: batch x 16x16x256 After pooling: batchx256,
> 
> Then we are left with only 256 value per image to be fed to the FC layers, which is very few I think.
> 
> In the original BT paper, they also do an AVG pooling (well, actually it's built in into the Resnet they use), before pooling: batch x2048x7x7 after pooling: batch x2048x1x1
> 
> As you can see, original paper has much more data per image (2048 instead of 256)
> 
>Hello, could you please share the complete version of BT-Unet code? I always report errors when running the code provided by the author. Thank you very much. 1934024210@qq.com
